sudo: required
services:
    - docker

script:
    - docker build -t ericc06/node .
    - docker images ericc06/node

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
    provider: script
    script: docker push eric06/testnode
    on:
        branch: main